// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:205b8fa5-559d-4ade-a410-4e6e9e3e94bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1Hk3UIA8R",
    "aws_user_pools_web_client_id": "3jic5vv083mq811ic6vuaj0jkh",
    "oauth": {},
    "aws_content_delivery_bucket": "proj-20191221173552-hostingbucket-env",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2mikcj1hph1y6.cloudfront.net"
};


export default awsmobile;
